#!/usr/bin/env python3
"""Build presidential_info.json for presidential elections within the calendar window."""

from __future__ import annotations

import json
import re
from datetime import date, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ELECTIONS_PATH = ROOT / "data" / "elections.json"
MARKETS_PATH = ROOT / "data" / "config" / "presidential_markets.json"
OUTPUT_PATH = ROOT / "data" / "curated" / "presidential_info.json"

WINDOW_MONTHS = 12
PRESIDENTIAL_LABEL_RE = re.compile(r"^President(?:\s+—\s+Round\s+\d+)?$", re.I)


def load_json(path: Path) -> dict | list:
    with path.open(encoding="utf-8") as fh:
        return json.load(fh)


def save_json(path: Path, data: dict) -> None:
    with path.open("w", encoding="utf-8") as fh:
        json.dump(data, fh, indent=2, ensure_ascii=False)
        fh.write("\n")


def window_end(today: date) -> date:
    return today + timedelta(days=WINDOW_MONTHS * 30)


def presidential_countries_in_window(today: date | None = None) -> set[str]:
    today = today or date.today()
    end = window_end(today)
    countries: set[str] = set()

    for item in load_json(ELECTIONS_PATH):
        election_date = date.fromisoformat(item["date"])
        if election_date < today or election_date > end:
            continue
        country_code = item.get("country_code")
        if not country_code:
            continue

        if item.get("type") == "presidential":
            countries.add(country_code)
            continue

        for section in item.get("sections") or []:
            for office in section.get("offices") or []:
                if PRESIDENTIAL_LABEL_RE.match(office):
                    countries.add(country_code)
                    break

    return countries


def main() -> None:
    meta = load_json(MARKETS_PATH)
    elections = meta.get("elections", {})
    needed = sorted(presidential_countries_in_window())

    output: dict = {
        "_comment": (
            "Generated by scripts/generate_presidential_info.py for presidential elections "
            f"within the next {WINDOW_MONTHS} months. Display rules: docs/events.md#presidential-info-popover"
        ),
        "_window_months": WINDOW_MONTHS,
    }

    for country_code in needed:
        if country_code in elections:
            output[country_code] = elections[country_code]

    save_json(OUTPUT_PATH, output)
    print(
        f"Wrote {len([k for k in output if not k.startswith('_')])} country entries "
        f"to {OUTPUT_PATH.relative_to(ROOT)}"
    )


if __name__ == "__main__":
    main()
