#!/usr/bin/env python3
"""Build us_governor_info.json for US gubernatorial elections within the calendar window."""

from __future__ import annotations

import json
from datetime import date, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ELECTIONS_PATH = ROOT / "data" / "curated" / "us_elections.json"
MARKETS_PATH = ROOT / "data" / "config" / "us_governor_markets.json"
OUTPUT_PATH = ROOT / "data" / "curated" / "us_governor_info.json"

WINDOW_MONTHS = 12


def load_json(path: Path) -> dict | list:
    with path.open(encoding="utf-8") as fh:
        return json.load(fh)


def save_json(path: Path, data: dict) -> None:
    with path.open("w", encoding="utf-8") as fh:
        json.dump(data, fh, indent=2, ensure_ascii=False)
        fh.write("\n")


def window_end(today: date) -> date:
    return today + timedelta(days=WINDOW_MONTHS * 30)


def governor_states_in_window(today: date | None = None) -> set[str]:
    today = today or date.today()
    end = window_end(today)
    states: set[str] = set()

    for item in load_json(ELECTIONS_PATH):
        if item.get("title") != "Governor":
            continue
        election_date = date.fromisoformat(item["date"])
        if election_date < today or election_date > end:
            continue
        state_code = item.get("state_code")
        if state_code:
            states.add(state_code)

    return states


def main() -> None:
    meta = load_json(MARKETS_PATH)
    markets = meta.get("markets", {})
    needed = sorted(governor_states_in_window())

    output: dict = {
        "_comment": (
            "Generated by scripts/generate_us_governor_info.py for US gubernatorial elections "
            f"within the next {WINDOW_MONTHS} months. Display rules: docs/events.md#us-governor-info-popover"
        ),
        "_window_months": WINDOW_MONTHS,
    }

    for state_code in needed:
        if state_code in markets:
            output[state_code] = markets[state_code]

    save_json(OUTPUT_PATH, output)
    print(
        f"Wrote {len([k for k in output if not k.startswith('_')])} state entries "
        f"to {OUTPUT_PATH.relative_to(ROOT)}"
    )


if __name__ == "__main__":
    main()
