#!/usr/bin/env python3
"""Build us_senate_info.json for US Senate general elections within the calendar window."""

from __future__ import annotations

import json
from datetime import date, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ELECTIONS_PATH = ROOT / "data" / "curated" / "us_elections.json"
MARKETS_PATH = ROOT / "data" / "config" / "us_senate_markets.json"
PRIMARY_MARKETS_PATH = ROOT / "data" / "config" / "us_primary_markets.json"
OUTPUT_PATH = ROOT / "data" / "curated" / "us_senate_info.json"

WINDOW_MONTHS = 12

# Class II Senate seats up in 2026 (mirrors scripts/generate_us_primaries.py).
SENATE_2026 = {
    "AL", "AK", "AR", "CO", "DE", "GA", "IA", "ID", "IL", "KS", "KY", "LA",
    "MA", "ME", "MI", "MN", "MS", "MT", "NC", "NE", "NH", "NJ", "NM", "OK",
    "OR", "RI", "SC", "SD", "TN", "TX", "VA", "WV", "WY",
}

STATE_SLUG_PREFIX = {
    "AL": "alabama",
    "AK": "alaska",
    "AR": "arkansas",
    "CO": "colorado",
    "GA": "georgia",
    "IA": "iowa",
    "ID": "idaho",
    "IL": "illinois",
    "KS": "kansas",
    "ME": "maine",
    "MA": "massachusetts",
    "MI": "michigan",
    "MN": "minnesota",
    "NE": "nebraska",
    "NH": "new-hampshire",
    "NM": "new-mexico",
    "OK": "oklahoma",
    "OR": "oregon",
    "RI": "rhode-island",
    "SC": "south-carolina",
    "SD": "south-dakota",
    "TN": "tennessee",
    "TX": "texas",
    "WY": "wyoming",
}

PRIMARY_PARTY_TO_SENATE = {
    "Republican": "Republican",
    "Democratic": "Democrat",
}


def load_json(path: Path) -> dict | list:
    with path.open(encoding="utf-8") as fh:
        return json.load(fh)


def save_json(path: Path, data: dict) -> None:
    with path.open("w", encoding="utf-8") as fh:
        json.dump(data, fh, indent=2, ensure_ascii=False)
        fh.write("\n")


def window_end(today: date) -> date:
    return today + timedelta(days=WINDOW_MONTHS * 30)


def senate_states_in_window(today: date | None = None) -> set[str]:
    today = today or date.today()
    end = window_end(today)
    states: set[str] = set()

    for item in load_json(ELECTIONS_PATH):
        state_code = item.get("state_code")
        if not state_code or state_code not in SENATE_2026:
            continue
        election_date = date.fromisoformat(item["date"])
        if election_date < today or election_date > end:
            continue
        states.add(state_code)

    return states


def default_nominee_slugs(state_code: str) -> dict[str, str]:
    prefix = STATE_SLUG_PREFIX.get(state_code)
    if not prefix:
        return {}

    return {
        "Republican": f"{prefix}-republican-senate-primary-winner",
        "Democrat": f"{prefix}-democratic-senate-primary-winner",
    }


def primary_nominee_slugs(state_code: str, primary_meta: dict) -> dict[str, str]:
    senate = primary_meta.get("polymarket_slugs", {}).get(state_code, {}).get("Senate", {})
    slugs: dict[str, str] = {}

    for party, slug in senate.items():
        if party.startswith("_") or not isinstance(slug, str):
            continue
        senate_party = PRIMARY_PARTY_TO_SENATE.get(party)
        if senate_party:
            slugs[senate_party] = slug

    return slugs


def build_state_entry(
    state_code: str,
    market_config: dict,
    meta: dict,
    primary_meta: dict,
) -> dict:
    entry = dict(market_config)
    incumbents = meta.get("incumbents", {}).get(state_code)

    nominee_slugs = default_nominee_slugs(state_code)
    nominee_slugs.update(primary_nominee_slugs(state_code, primary_meta))

    if nominee_slugs and entry.get("odds_format") != "candidates":
        entry["nominee_slugs"] = nominee_slugs

    if incumbents:
        if entry.get("odds_format") == "candidates":
            for party, surname in incumbents.items():
                if entry.get("incumbent"):
                    break
                entry.setdefault("incumbent", surname)
        else:
            entry["incumbents"] = incumbents

    return entry


def main() -> None:
    meta = load_json(MARKETS_PATH)
    markets = meta.get("markets", {})
    primary_meta = load_json(PRIMARY_MARKETS_PATH)
    needed = sorted(senate_states_in_window())

    output: dict = {
        "_comment": (
            "Generated by scripts/generate_us_senate_info.py for US Senate general elections "
            f"within the next {WINDOW_MONTHS} months. Display rules: docs/events.md#us-senate-info-popover"
        ),
        "_window_months": WINDOW_MONTHS,
    }

    for state_code in needed:
        if state_code in markets:
            output[state_code] = build_state_entry(state_code, markets[state_code], meta, primary_meta)

    save_json(OUTPUT_PATH, output)
    print(
        f"Wrote {len([k for k in output if not k.startswith('_')])} state entries "
        f"to {OUTPUT_PATH.relative_to(ROOT)}"
    )


if __name__ == "__main__":
    main()
