#!/usr/bin/env python3
"""Build us_primary_info.json for US primaries within the next N months."""

from __future__ import annotations

import json
from datetime import date, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PRIMARIES_PATH = ROOT / "data" / "curated" / "us_primaries.json"
MARKETS_PATH = ROOT / "data" / "config" / "us_primary_markets.json"
OUTPUT_PATH = ROOT / "data" / "curated" / "us_primary_info.json"

WINDOW_MONTHS = 3


def load_json(path: Path) -> dict:
    with path.open(encoding="utf-8") as fh:
        return json.load(fh)


def save_json(path: Path, data: dict) -> None:
    with path.open("w", encoding="utf-8") as fh:
        json.dump(data, fh, indent=2, ensure_ascii=False)
        fh.write("\n")


def window_end(today: date) -> date:
    """Approximate three calendar months ahead."""
    month = today.month + WINDOW_MONTHS
    year = today.year + (month - 1) // 12
    month = ((month - 1) % 12) + 1
    day = min(today.day, 28)
    return date(year, month, day)


def primaries_in_window(today: date | None = None) -> set[tuple[str, str]]:
    today = today or date.today()
    end = window_end(today)
    needed: set[tuple[str, str]] = set()

    for item in load_json(PRIMARIES_PATH):
        if item.get("type") != "primary":
            continue
        primary_date = date.fromisoformat(item["date"])
        if primary_date < today or primary_date > end:
            continue
        state_code = item.get("state_code")
        for office in item.get("offices") or []:
            if state_code and office:
                needed.add((state_code, office))

    return needed


def build_party_config(
    state_code: str,
    office: str,
    slugs: dict,
    incumbents: dict,
) -> dict[str, dict]:
    parties: dict[str, dict] = {}
    office_slugs = slugs.get(state_code, {}).get(office, {})
    office_incumbents = incumbents.get(state_code, {}).get(office, {})

    for party in ("Republican", "Democratic"):
        party_config: dict = {}
        if party in office_slugs:
            party_config["polymarket_slug"] = office_slugs[party]
        elif party in office_incumbents:
            party_config["incumbent"] = office_incumbents[party]

        if party_config:
            parties[party] = party_config

    return parties


def build_entry(
    state_code: str,
    office: str,
    meta: dict,
    slugs: dict,
    incumbents: dict,
) -> dict:
    type_cfg = meta["primary_types"][state_code]
    note_key = type_cfg["note_key"]
    entry: dict = {
        "primary_format": type_cfg.get("format", "party"),
        "primary_type": type_cfg["type"],
        "primary_type_label": meta["type_labels"][note_key],
        "primary_type_note": meta["type_notes"][note_key],
    }

    office_slugs = slugs.get(state_code, {}).get(office, {})
    if entry["primary_format"] == "top-four":
        if "_slug" in office_slugs:
            entry["polymarket_slug"] = office_slugs["_slug"]
        return entry

    parties = build_party_config(state_code, office, slugs, incumbents)
    if parties:
        entry["parties"] = parties

    return entry


def main() -> None:
    meta = load_json(MARKETS_PATH)
    slugs = meta.get("polymarket_slugs", {})
    incumbents = meta.get("incumbents", {})
    needed = sorted(primaries_in_window())

    output: dict = {
        "_comment": (
            "Generated by scripts/generate_us_primary_info.py for primaries "
            f"within the next {WINDOW_MONTHS} months. Display rules: docs/events.md#primary-info-popover"
        ),
        "_window_months": WINDOW_MONTHS,
    }

    for state_code, office in needed:
        if state_code not in meta["primary_types"]:
            continue
        output.setdefault(state_code, {})[office] = build_entry(
            state_code, office, meta, slugs, incumbents
        )

    save_json(OUTPUT_PATH, output)
    print(f"Wrote {len(needed)} state/office entries to {OUTPUT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
