#!/usr/bin/env python3
"""Build mayoral_info.json for mayoral elections within the calendar window."""

from __future__ import annotations

import json
from datetime import date, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ELECTIONS_PATH = ROOT / "data" / "elections.json"
MARKETS_PATH = ROOT / "data" / "config" / "mayoral_markets.json"
OUTPUT_PATH = ROOT / "data" / "curated" / "mayoral_info.json"

WINDOW_MONTHS = 12


def load_json(path: Path) -> dict | list:
    with path.open(encoding="utf-8") as fh:
        return json.load(fh)


def save_json(path: Path, data: dict) -> None:
    with path.open("w", encoding="utf-8") as fh:
        json.dump(data, fh, indent=2, ensure_ascii=False)
        fh.write("\n")


def window_end(today: date) -> date:
    return today + timedelta(days=WINDOW_MONTHS * 30)


def mayoral_market_keys_in_window(today: date | None = None) -> set[str]:
    today = today or date.today()
    end = window_end(today)
    keys: set[str] = set()
    local_titles = {"Mayor", "By-election"}

    for item in load_json(ELECTIONS_PATH):
        if item.get("title") not in local_titles:
            continue
        election_date = date.fromisoformat(item["date"])
        if election_date < today or election_date > end:
            continue
        city_code = item.get("city_code")
        country_code = item.get("country_code")
        if city_code:
            keys.add(city_code)
        if country_code:
            keys.add(country_code)

    return keys


def main() -> None:
    meta = load_json(MARKETS_PATH)
    markets = meta.get("markets", {})
    needed = sorted(mayoral_market_keys_in_window())

    output: dict = {
        "_comment": (
            "Generated by scripts/generate_mayoral_info.py for mayoral elections "
            f"within the next {WINDOW_MONTHS} months. Display rules: docs/events.md#mayoral-info-popover"
        ),
        "_window_months": WINDOW_MONTHS,
    }

    for city_code in needed:
        if city_code in markets:
            output[city_code] = markets[city_code]

    save_json(OUTPUT_PATH, output)
    print(
        f"Wrote {len([k for k in output if not k.startswith('_')])} market entries "
        f"to {OUTPUT_PATH.relative_to(ROOT)}"
    )


if __name__ == "__main__":
    main()
